### ISSUE TITLE
Chrome refuses script when calling from github

### ISSUE THREAD

**Issue by frankcash** [raimohanska/Bacon.UI.js#28]
This problem only appears to be in Chrome/Chromium (I'm using 41.0.2272)
code:
``` html
<script src="https://raw.githubusercontent.com/raimohanska/Bacon.UI.js/master/Bacon.UI.js"></script>
```
error:
```
Refused to execute script from 'https://raw.githubusercontent.com/raimohanska/Bacon.UI.js/master/Bacon.UI.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
```
After looking farther I found [this](https://code.google.com/p/chromium/issues/detail?id=180007) issue on Chromium issue tracker.  

It appears [RawGit](http://rawgit.com/) can serve Github files with the proper headers for this.  

Thus one's html should look like:
```html
<script src="https://rawgit.com/raimohanska/Bacon.UI.js/master/Bacon.UI.js"></script>
```

Would it be possible to update the README.md to include information about this so other's don't have to spend time figuring it out like I did?  I have no problem submitting a pull request to update it :smile_cat:.

**Comment by raimohanska** [comment]
I'm no longer maintaining this library, please use bacon.jquery or fork this one, if you like. Happy hacking!
